version: '3.8'

services:
  gemini-agentic:
    build: .
    container_name: ultra-gemini-agentic
    restart: unless-stopped
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - gemini-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: ultra-gemini-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - gemini-agentic
    networks:
      - gemini-network

  prometheus:
    image: prom/prometheus:latest
    container_name: ultra-gemini-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - gemini-network

networks:
  gemini-network:
    driver: bridge

volumes:
  gemini-data:
  gemini-logs:
