# Autonomous Bug Hunter Configuration
# AI-Powered Vulnerability Discovery and Exploitation

autonomous:
  enabled: true
  max_concurrent_targets: 5
  exploitation_timeout: 7200
  learning_enabled: true
  zero_day_hunting: true
  continuous_monitoring: true
  adaptive_exploitation: true

ai:
  openai_key: ""
  anthropic_key: ""
  gemini_key: ""
  model: "gpt-4"
  max_tokens: 2000
  temperature: 0.7
  enable_multi_provider: true

exploitation:
  aggressive_mode: true
  evasion_enabled: true
  polymorphic_payloads: true
  business_logic_testing: true
  zero_day_detection: true
  advanced_techniques:
    - race_conditions
    - privilege_escalation
    - data_manipulation
    - session_manipulation
    - protocol_manipulation

vulnerability_discovery:
  xss_detection: true
  sqli_detection: true
  business_logic_flaws: true
  authentication_bypass: true
  authorization_bypass: true
  input_validation_bypass: true
  novel_attack_vectors: true

tools:
  # Advanced reconnaissance
  subfinder: true
  amass: true
  assetfinder: true
  httpx: true
  nuclei: true
  ffuf: true
  gobuster: true
  dirb: true
  
  # Exploitation tools
  sqlmap: true
  xsser: true
  dalfox: true
  arachni: true
  nikto: true
  
  # Custom exploitation
  custom_payloads: true
  ai_generated_payloads: true
  polymorphic_evasion: true

dashboard:
  port: 5001
  host: "0.0.0.0"
  debug: false
  theme: "dark"
  real_time_updates: true

output:
  base_dir: "autonomous_results"
  reports_dir: "reports"
  exploits_dir: "exploits"
  payloads_dir: "payloads"
  intelligence_dir: "intelligence"
  zero_day_dir: "zero_day"
  auto_cleanup_days: 30

learning:
  enable_pattern_recognition: true
  adaptive_payloads: true
  success_rate_tracking: true
  technique_optimization: true
  cross_target_learning: true

zero_day_hunting:
  enabled: true
  novel_technique_detection: true
  protocol_analysis: true
  behavioral_analysis: true
  signature_evasion: true
  polymorphic_techniques: true 