# Exploitation & Post-Exploitation Configuration
# Configure safety controls, exploit modules, and reporting settings

safety:
  enabled: true
  require_consent: true
  dry_run_mode: true
  max_concurrent_sessions: 3
  session_timeout_minutes: 30
  payload_validation: true
  output_encryption: false

exploitation:
  default_timeout: 60
  retry_attempts: 3
  payload_validation: true
  output_encryption: false
  max_payload_size: 1048576  # 1MB

modules:
  rce:
    enabled: true
    timeout: 30
    safety_checks: true
    methods:
      - command_injection
      - file_upload
      - deserialization
      - buffer_overflow
  
  sqli:
    enabled: true
    timeout: 45
    safety_checks: true
    methods:
      - boolean_based
      - time_based
      - union_based
      - error_based
  
  xss:
    enabled: true
    timeout: 20
    safety_checks: true
    methods:
      - reflected
      - stored
      - dom_based
  
  privesc:
    enabled: true
    timeout: 60
    safety_checks: true
    platforms:
      - linux
      - windows
    methods:
      linux:
        - sudo_exploitation
        - suid_exploitation
        - kernel_exploitation
        - cron_jobs
      windows:
        - token_manipulation
        - service_exploitation
        - registry_exploitation
        - dll_hijacking
  
  lateral:
    enabled: true
    timeout: 90
    safety_checks: true
    methods:
      - ssh_bruteforce
      - smb_exploit
      - rdp_exploit
      - winrm_exploit
      - psexec
  
  exfil:
    enabled: true
    timeout: 120
    safety_checks: true
    data_types:
      - files
      - database
      - credentials
      - configs
      - logs
    methods:
      - http_post
      - dns_tunneling
      - icmp_tunneling
      - ftp_transfer

reporting:
  auto_generate: true
  include_payloads: false
  encrypt_sensitive: true
  export_formats:
    - json
    - html
    - pdf
  include_screenshots: false
  include_network_captures: false

audit:
  enabled: true
  log_all_actions: true
  retention_days: 365
  encryption: false
  export_audit_logs: true

targets:
  allowed_domains: []
  blocked_domains: []
  allowed_ips: []
  blocked_ips: []
  scope_validation: true

payloads:
  custom_payloads: []
  payload_templates:
    rce:
      - "|whoami"
      - ";id"
      - "`whoami`"
    sqli:
      - "' OR '1'='1"
      - "' UNION SELECT 1,2,3--"
      - "' AND SLEEP(5)--"
    xss:
      - "<script>alert('XSS')</script>"
      - "<img src=x onerror=alert('XSS')>"
      - "javascript:alert('XSS')"

notifications:
  email:
    enabled: false
    smtp_server: smtp.gmail.com
    smtp_port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    recipients: []
    notify_on:
      - exploit_success
      - privesc_success
      - data_exfiltrated
  
  slack:
    enabled: false
    webhook_url: ${SLACK_WEBHOOK_URL}
    channel: #exploitation
    notify_on:
      - exploit_success
      - privesc_success
  
  webhook:
    enabled: false
    url: ${WEBHOOK_URL}
    headers: {}
    notify_on:
      - exploit_success
      - privesc_success 