# Kali Bug Hunter Configuration
# Optimized for Kali Linux - Simplified for Personal Bug Bounty Hunting

kali:
  tools_path: "/usr/bin"
  enable_kali_tools: true
  auto_update: true
  theme: "dark"

scanning:
  default_scan_type: "comprehensive"
  max_concurrent_scans: 3
  scan_timeout: 3600
  enable_ai_analysis: true
  quick_scan_timeout: 300
  comprehensive_scan_timeout: 1800

tools:
  # Reconnaissance
  nmap: true
  masscan: true
  subfinder: true
  amass: true
  theharvester: true
  dnsrecon: true
  whatweb: true
  wafw00f: true
  shodan: false  # Needs API key
  gobuster: true
  dirb: true
  assetfinder: true
  eyewitness: true
  spiderfoot: true

  # Vulnerability Scanning
  nuclei: true
  httpx: true
  nikto: true
  wpscan: true
  joomscan: true
  sqlmap: true
  xsser: true
  arachni: true
  ffuf: true
  dalfox: true

  # Exploitation
  metasploit: true
  hydra: true
  medusa: true
  patator: true
  crackmapexec: true
  responder: true
  impacket: true

  # Post-Exploitation/Analysis
  hashcat: true
  john: true
  binwalk: true
  strings: true
  exiftool: true
  steghide: true
  foremost: true
  volatility: true
  radare2: true
  gdb: true

  # Wireless/Network
  aircrack-ng: true
  reaver: true
  bettercap: true
  kismet: true

  # OSINT/Other
  maltego: false  # GUI, optional
  recon-ng: true
  sherlock: true
  social-engineer-toolkit: true

ai:
  provider: "openai"  # openai, anthropic, gemini
  api_key: ""
  model: "gpt-4"
  enable_auto_analysis: true
  max_tokens: 2000

dashboard:
  port: 5000
  host: "0.0.0.0"
  debug: false
  theme: "dark"
  auto_refresh: 30

output:
  base_dir: "kali_results"
  reports_dir: "reports"
  scans_dir: "scans"
  payloads_dir: "payloads"
  exports_dir: "exports"
  auto_cleanup_days: 30

monitoring:
  enable_alerts: true
  alert_email: ""
  scan_interval: 3600
  max_retries: 3

# Kali Linux specific optimizations
kali_optimizations:
  use_kali_repos: true
  auto_install_missing: true
  optimize_performance: true
  enable_gpu_acceleration: false
  memory_limit: "4G"
  cpu_limit: 4 