# Kali Bug Hunter Configuration
# Optimized for Kali Linux

kali:
  tools_path: "/usr/bin"
  enable_kali_tools: true
  auto_update: true
  theme: "dark"

scanning:
  default_scan_type: "comprehensive"
  max_concurrent_scans: 3
  scan_timeout: 3600
  enable_ai_analysis: true
  quick_scan_timeout: 300
  comprehensive_scan_timeout: 1800

tools:
  # Core reconnaissance tools
  nmap: true
  nuclei: true
  ffuf: true
  subfinder: true
  amass: true
  httpx: true
  
  # Additional tools (optional)
  gobuster: false
  dirb: false
  nikto: false
  sqlmap: false
  xsser: false

ai:
  provider: "openai"  # openai, anthropic, gemini
  api_key: ""
  model: "gpt-4"
  enable_auto_analysis: true
  max_tokens: 2000

dashboard:
  port: 5000
  host: "0.0.0.0"
  debug: false
  theme: "dark"
  auto_refresh: 30

security:
  enable_encryption: true
  session_timeout: 3600
  max_login_attempts: 5
  require_ssl: false

output:
  base_dir: "kali_results"
  reports_dir: "reports"
  scans_dir: "scans"
  payloads_dir: "payloads"
  exports_dir: "exports"
  auto_cleanup_days: 30

monitoring:
  enable_alerts: true
  alert_email: ""
  scan_interval: 3600
  max_retries: 3

# Kali Linux specific optimizations
kali_optimizations:
  use_kali_repos: true
  auto_install_missing: true
  optimize_performance: true
  enable_gpu_acceleration: false
  memory_limit: "4G"
  cpu_limit: 4 