alert_on_high_failure_rate: true
api_key_rotation_days: 30
api_rate_limit: 1.0
api_timeout: 30.0
audit_logging: true
backup_interval_hours: 6
cache_ttl_seconds: 300
database_path: ultra_gemini_production.db
debug_mode: false
enable_encryption: true
enable_monitoring: true
environment: production
execution_timeout: 60.0
failure_rate_threshold: 0.1
gemini_api_key: null
gemini_model: gemini-pro
log_level: INFO
max_concurrent_campaigns: 5
max_cpu_usage_percent: 80.0
max_database_size_mb: 1000
max_iterations_per_campaign: 10
max_memory_usage_mb: 4096
max_network_bandwidth_mbps: 100.0
performance_degradation_threshold: 0.2
rate_limiting: true
